### ISSUE TITLE
Research chart.js or suitable alternative

### ISSUE THREAD

**Issue by lucsedirae** [lucsedirae/open-house-crm#51]
Would like to have a component that can display transaction data in the user's dashboard. Try out chart.js and any other charting libraries that look promising and build out a chart component that can be inserted into the business summary page

**Comment by serjykalstryke** [comment]
chart.js seems like the way to go. Versatile and easy to import into react. I'll throw some tutorials into the hopper and figure out how to get our database info into charts, but doesn't seem like too much of a challenge.

**Comment by lucsedirae** [comment]
Chartjs implemented in current beta version
